FROM tomcat:9.0
ENV DB_HOST 192.168.1.110
ENV DB_USER alex
ENV DB_PASSWORD root
EXPOSE 9090
RUN rm -fr /usr/local/tomcat/webapps/TestServlet
COPY target/TestServlet-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/TestServlet.war
